### ISSUE TITLE
Not showing sessions to forget

### ISSUE THREAD

**Issue by sunscreem** [kind-work/login-notify#18]
Thanks for creating this plug in.

One issue I'm having:

I've added the login_notify field to users:

```yaml
sections:
  main:
    display: Main
    fields:
      -
        handle: name
        field:
          type: text
          display: Name
      -
        handle: email
        field:
          type: text
          input_type: email
          display: 'Email Address'
      -
        handle: roles
        field:
          type: user_roles
          mode: select
          width: 50
      -
        handle: groups
        field:
          type: user_groups
          mode: select
          width: 50
      -
        handle: login_notify
        field:
          display: 'Remembered Browsers'
          type: login_notify
          icon: login_notify
          listable: hidden
          instructions_position: above
```

Which is displaying:

![image](https://user-images.githubusercontent.com/7523595/150967012-ca1696f1-19a0-45fd-9d36-bc8dd675ddb1.png)

However I'm not seeing any browsers.

Here's the relavent section from my user yaml:

```yaml
name: 'Robert Cooper'
login_notify_valid_cookies:
  Rj0GgesruRzucyG1uGyNfQhxh6bgraFC:
    browser: Chrome
    os: 'Windows 10'
    ip: -- removed --
    at: 'Mon, Jan 17, 2022 8:58 PM'
  BvODVutvq2Cg1fwmizvK1hHP2FmTfpXs:
    browser: Chrome
    os: 'Windows 10'
    ip:  -- removed --
    at: 'Sun, Jan 23, 2022 7:00 PM'
```

And my versions:

```
Statamic 3.2.31 Pro
Laravel 8.78.1
PHP 8.0.10
doublethreedigital/duplicator 2.1.0
jonassiewertsen/statamic-external-link 1.4.1
kind-work/login-notify 1.1.0
legrisch/statamic-graphql-thumbnails 0.3.0
rias/statamic-color-swatches 2.0.5
```
